### PR TITLE
Add installation instructions for conda forge

### PR DESCRIPTION
**Pull request by jaimergp**
Will close https://github.com/openmm/openmm-plumed/issues/6

### CODE REVIEW

**Comment by raimis** [comment]
@jaimergp is this finished?

**Comment by jaimergp** [comment]
I tested on Linux and it works. It'd be nice to check if MacOS works as expected too:

```
conda create -n openmm-plumed-test -c conda-forge openmm-plumed
conda activate openmm-plumed-test
python -c "import openmmplumed"  # should return nothing
$CONDA_PREFIX/share/openmm-plumed/tests/TestReferencePlumedForce
```

**Comment by tonigi** [comment]
It seems to work on MacOS too :)

**Comment by raimis** [comment]
I think, we can merge this.

**Comment by jaimergp** [comment]
@peastman Ready to merge :)

**Pull request merged**
